account/urls.py
from django.contrib import admin
from django.urls import path

from . import views

app_name='account'
urlpatterns = [
    path('login',views.login_user,name='login_user'),
    path('signup',views.signup,name='signup'),
    path('logout',views.logout_user,name='logout_user'),
    path('activate',views.activate, name='activate'),
    path('resend_token',views.resend_token,name='resend_token'),
    path('my-profile',views.my_account,name="my_account"),
    path('change-password',views.change_password,name='change_password')
]

events/urls.py
from django.contrib import admin
from django.urls import path

from . import views

app_name='events'
urlpatterns = [
    path('event-list',views.all_events,name="all_events"),
    path('event-add<int:id>',views.events_add,name="edit_event"),
    path('<int:id>/delete/', views.delete_event, name='delete_event'),

    path('event-add',views.events_add,name="eventadd"),
    path('view-event/<int:id>',views.view_event,name='view_event'),

    #homepage view of event
    path('all-events-index',views.index_all_events,name='index_all_events'),
    path('homepage-view-event/<int:id>',views.homepage_view_event,name='homepage_view_event'),
    #for participation
    path('participate/<int:event_id>/', views.participate, name='participate'),
    # path('participation/', views.regunauth, name="participation"),
    #payment for events
    path('event/payment/process/<int:event_id>/', views.auth_payment_process, name='auth_payment_process'),
    path('event/payment/process/<int:event_id>/<str:name>/<str:email>/<int:phone>', views.unauth_payment_process, name='unauth_payment_process'),
    # path('event/payment/done/', views.payment_done, name='payment_done'),

    # path('participation-list/', views.participatorlist, name='participation_list'),

    path('participation_list/', views.participatorlist, name='participation_list'),
    # URL pattern for showing participation list for a specific event
    path('participation_list/<int:event_id>/', views.participatorlist, name='event_participation_list'),
    path('not_going_participants/<int:event_id>/', views.not_going_participants, name='not_going_participants'),
]

management/urls.py
from django.contrib import admin
from django.urls import path
from . import views
from .insert import ImportBulkData
app_name='management'
urlpatterns = [
    path('',views.index, name='index'),
    path('user-dashboard',views.user_dashboard,name='user_dashboard'),
    path('membership-guidelines',views.membership_guidelines,name='membership_guidelines'),
    path('new-membership',views.new_membership,name='new_membership'),
    #General Membeership Forms 
    path('new-membership/general-membership-personal-info',views.general_membership_personal,name='general_membership_personal'),
    #Registration Completion 
    path('new-membership/complete-national-info/<int:id>',views.complete_registration_national_document,name='complete_registration_national_document'),
    path('new-membership/complete-educational-info/<int:id>',views.complete_registration_educational_document,name='complete_registration_educational_document'),
    # Lifetime Membership 
    path('new-membership/general-membership-personal-info/<int:id>',views.general_membership_personal,name='lifetime_membership_personal'),
    #Student Mambership 
    path('new-membership/student-membership-personal-info',views.student_membership_personal,name='student_membership_personal'),
    #Institutional Membership
    path('new-membership/institutional-membership-form',views.institutional_membership_details,name='institutional_membership_details'),
    path('new-membership/institutional-membership-documents/<int:id>',views.complete_institutional_membership,name='complete_institutional_membership'),

    #Tabular membership Vies 
    path('view-general-membership-list',views.view_general_membership_list,name='view_general_membership_list'),
    path('view-students-membership-list',views.view_student_membership_list,name='view_student_membership_list'),
    path('view-lifetime-membership-list',views.view_lifetime_membership_list,name='view_lifetime_membership_list'),
    path('view-institutional-membership-list',views.view_institutional_membership_list,name='view_institutional_membership_list'),
    #verify membership
    path('verify-membership/<int:id>',views.verify_membership,name='verify_membership'),
    #reject membership
    path('reject-membership/<int:id>',views.reject_membership,name='reject_membership'),
    #Approved Views
    path('view-all-approved-membership_list',views.all_approved_membership_list,name='all_approved_membership_list'),
    path('view-general-approved-membership_list',views.general_approved_membership_list,name='general_approved_membership_list'),
    path('view-lifetime-approved-membership_list',views.lifetime_approved_membership_list,name='lifetime_approved_membership_list'),
    path('view-student-approved-membership_list',views.student_approved_membership_list,name='student_approved_membership_list'),
    path('view-lifetime-approved-membership_list',views.lifetime_approved_membership_list,name='institutional_approved_membership_list'),
    # all rejected
    path('rejected-membership-list',views.rejected_membership_list, name='rejected_membership_list'),
    #view membership
    path('view-membership/membership/<int:id>',views.view_membership,name='view_membership'),
    #edit membership
    path('edit-membership-instance/<int:id>',views.edit_membership,name='edit_membership'),
    path('edit-membership-personal_info/<int:id>',views.edit_personal_info,name='edit_personal_info'),
    path('edit-membership-educational_info/<int:id>',views.edit_educational_info,name='edit_educational_info'),
    path('edit-membership-documents_info/<int:id>',views.edit_national_info,name='edit_national_info'),
    path('edit-institutional-info/<int:id>',views.edit_institutional_info,name='edit_institutional_info'),
    path('edit-institutional-documents/<int:id>',views.edit_institutional_documents,name='edit_institutional_documents'),
    #Payment information
    path('membership/payment',views.payment, name='payment'),
    path("payment/initiate-khalti/", views.initiate_khalti, name="initiate_khalti"),
    path('membership/payment-verification',views.payment_verification,name='payment_verification'),
    #resubmit_membership
    path('resubmit-membership/<int:id>',views.resubmit_membership,name='resubmit_membership'),

    #Tabular View Index
    path('student-members',views.student_members,name='student_members'),
    path('lifetime-members',views.lifetime_members,name='lifetime_members'),
    path('general-members',views.general_members,name='general_members'),
    path('institutional-members',views.institutional_members,name='institutional_members'),
    path('honorary-members', views.honorary_members, name='honorary_members'),
    #upgrade request table
    path('upgrade-to-lifetime-members_list',views.lifetime_upgrade_request_list,name='upgrade_lifetime_membership_list'),
    path('upgrade-to-general-members_list',views.general_upgrade_request_list,name='upgrade_general_membership_list'),
    #upgrade Membership
    path('upgrade-to-general-members',views.upgrade_to_general_membership,name='upgrade_to_general_membership'),
    path('upgrade-to-lifetime-members',views.upgrade_to_lifetime_membership,name='upgrade_to_lifetime_membership'),
    path('verify-upgrade/<int:id>',views.verify_upgrade,name='verify_upgrade'),

    #renew
    path('renew-general-membership/', views.renew_general_membership, name='renew_general_membership'),
    path('renew-general-membership-list',views.general_renew_request_list,name='general_renew_request_list'),
    path('renew-verify/<int:id>',views.verify_renew,name='verify_renew'),

    ##Faqs
    path('all-faqs',views.all_faqs,name='all_faqs'),
    path('create-faq',views.create_faq,name='create_faq'),
    path('import-bulk-data',ImportBulkData.as_view(),name='import_bulk_data')

]

membership/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf import settings
from django.contrib.auth import views as auth_views
from account.views import CustomPasswordResetView
from django.conf.urls.static import static

urlpatterns = [
    path("admin/", admin.site.urls),
    path('',include('management.urls')),
    path('account/',include('account.urls')),
    path('notifications/',include('notification.urls')),
    path('events',include('events.urls')),
     path(
        "reset-password/",
        CustomPasswordResetView.as_view(
            template_name="account/forget_password.html"
        ),
        name="reset_password",
    ),
    path(
        "password_reset/done/",
        auth_views.PasswordResetDoneView.as_view(
            template_name='account/password_reset_done.html'
        ),
        name="password_reset_done",
    ),
    path(
        "reset/<uidb64>/<token>/",
        auth_views.PasswordResetConfirmView.as_view(
            template_name="account/reset_password.html"
        ),
        name='password_reset_confirm',
    ),
    path(
        "reset/done/",
        auth_views.PasswordResetCompleteView.as_view(
            template_name='account/password_reset_complete.html'
        ),
        name="password_reset_complete",
    ),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

management/forms.py
from django import forms
from .models import GeneralMembership,InstitutionalMembership,EducationalDocuments, Payment,FAQ,Membership
from django.contrib.auth.hashers import make_password
from django.core.exceptions import ValidationError
from . import choices
from datetime import date, timedelta


class PersonalInfoForm(forms.Form):
    salutation = forms.ChoiceField(choices=choices.SALUTATION_CHOICES)
    name_of_applicant = forms.CharField(
        max_length=200,
        error_messages={
            'required': 'Please enter name of applicant.',
        })
   
    gender = forms.ChoiceField( choices=choices.GENDER_CHOICES)

    affiliation = forms.CharField(max_length=200,required=False)
    phone_number = forms.CharField(max_length=15)
   
    pp_photo = forms.ImageField(error_messages={
        'required':'Please upload Passport size photo'
    })
    def clean_pp_photo(self):
        pp_photo = self.cleaned_data.get('pp_photo')
        max_size = 1*1024*1024
        if pp_photo and (pp_photo.size>max_size):
            raise forms.ValidationError("Please upload photo less than 1 MB.")

        return pp_photo

class EditPersonalInfoForm(forms.Form):
    salutation = forms.ChoiceField(choices=choices.SALUTATION_CHOICES)
    name_of_applicant = forms.CharField(
        max_length=200,
        error_messages={
            'required': 'Please enter name of applicant.',
        })
   
    gender = forms.ChoiceField( choices=choices.GENDER_CHOICES)

    affiliation = forms.CharField(max_length=200,required=False)
    phone_number = forms.CharField(max_length=15)
   
    pp_photo = forms.ImageField(required=False)
    def clean_pp_photo(self):
        pp_photo = self.cleaned_data.get('pp_photo')
        max_size = 1*1024*1024
        if pp_photo and (pp_photo.size>max_size):
            raise forms.ValidationError("Please upload photo less than 1 MB.")

        return pp_photo
class NationalDocumentForm(forms.Form):
    nationality = forms.ChoiceField(choices=choices.COUNTRY_CHOICES)
    identity_card_no = forms.CharField(max_length=80)
    identity_issued_from = forms.CharField(max_length=150)
    permanent_address = forms.CharField(max_length=200)
    dob = forms.DateField(error_messages={
                           'required': 'Date of Birth is required.'
                         })
    identity_card_image = forms.FileField(error_messages={
        'required':'Please upload valid identity card'
    })
    
    def clean_dob(self):
        dob = self.cleaned_data.get('dob')
        if dob:
            # Calculate the date 10 years ago
            ten_years_ago = date.today() - timedelta(days=365 * 10)
            # Compare the date of birth with 10 years ago
            if dob > ten_years_ago:
                raise forms.ValidationError('You must be at least 10 years old to apply for membership')
        return dob.strftime('%Y-%m-%d') if dob else None

class EditNationalDocumentForm(forms.Form):
    nationality = forms.ChoiceField(choices=choices.COUNTRY_CHOICES)
    identity_card_no = forms.CharField(max_length=80)
    identity_issued_from = forms.CharField(max_length=150)
    permanent_address = forms.CharField(max_length=200)
    dob = forms.DateField(error_messages={
                           'required': 'Date of Birth is required.'
                         })
    identity_card_image = forms.FileField(required=False)
    def clean_dob(self):
        dob = self.cleaned_data.get('dob')
        if dob:
            # Calculate the date 10 years ago
            ten_years_ago = date.today() - timedelta(days=365 * 10)
            # Compare the date of birth with 10 years ago
            if dob > ten_years_ago:
                raise forms.ValidationError('You must be at least 10 years old to apply for membership')
        return dob.strftime('%Y-%m-%d') if dob else None
class EducationalForm(forms.Form):
    degree_type = forms.ChoiceField(choices=choices.DEGREE_TYPES)
    course = forms.CharField(max_length=200,
                            error_messages={
                               'required': 'Please enter name of applicant.',
                            })
    institution = forms.CharField(max_length=200,required=False)
    university = forms.CharField(max_length=200,
                                            error_messages={
                                                    'required': 'Bachelor University is mandatory.',
                                                })
    country = forms.ChoiceField(choices=choices.COUNTRY_CHOICES)
    passed_year = forms.CharField(max_length=4)
    educational_document = forms.FileField(error_messages={
        'required':'Please upload latest educational document'
    })

    work_experience = forms.CharField(widget=forms.Textarea,required=False)

class EditEducationalForm(forms.Form):
    degree_type = forms.ChoiceField(choices=choices.DEGREE_TYPES)
    course = forms.CharField(max_length=200,
                            error_messages={
                               'required': 'Please enter name of applicant.',
                            })
    institution = forms.CharField(max_length=200,required=False)
    university = forms.CharField(max_length=200,
                                            error_messages={
                                                    'required': 'Bachelor University is mandatory.',
                                                })
    country = forms.ChoiceField(choices=choices.COUNTRY_CHOICES)
    passed_year = forms.CharField(max_length=4)
    educational_document = forms.FileField(required=False)
    work_experience = forms.CharField(widget=forms.Textarea,required=False)

class InstitutionalForm(forms.Form):
    company_name = forms.CharField(max_length=200)
    company_address = forms.CharField(max_length=200)
    registration_no = forms.CharField(max_length=200)
    contact_person = forms.CharField(max_length=200)
    contact_number = forms.CharField(max_length=10)
    website = forms.CharField(max_length=250,required=False)
class EditInstitutionalForm(forms.Form):
    company_name = forms.CharField(max_length=200)
    company_address = forms.CharField(max_length=200)
    registration_no = forms.CharField(max_length=200)
    contact_person = forms.CharField(max_length=200)
    contact_number = forms.CharField(max_length=10)
    website = forms.CharField(max_length=250,required=False)
    working_field = forms.CharField(max_length=200)

class InstitutionalDocuments(forms.Form):
    logo = forms.ImageField(error_messages={
        'required':'Please upload logo of your company photo(Image)'
    })
    pan_document = forms.FileField(error_messages={
        'required':'Please upload PAN Document photo'
    })
    registration_document = forms.FileField(error_messages={
        'required':'Please upload  comapany registration Document'
    })
  
    working_field = forms.CharField(max_length=200)

class EditInstitutionalDocuments(forms.Form):
    logo = forms.ImageField(required=False)
    pan_document = forms.FileField(required=False)
    registration_document = forms.FileField(required=False)

class VerificationForm(forms.Form):
    membership_since = forms.CharField(max_length=4)
    membership_no = forms.CharField()
    
    
    
class PaymentForm(forms.ModelForm):
    class Meta:
        model = Payment
        fields = ["payment_ss"]


class FAQForm(forms.ModelForm):
    class Meta:
        model=FAQ
        fields='__all__'


class MembershipImportForm(forms.Form):
    excel_file = forms.FileField()
    def clean_excel_file(self):
        file = self.cleaned_data['excel_file']
        if not file.name.endswith('.xlsx'):
            raise ValidationError('Invalid file type: Only .xlsx files are supported.')
        return file

management/templates/management/complete_membership.html
<div class="alert alert-warning d-flex align-items-center fade show mt-4"
role="alert">
<span class="material-symbols-outlined me-2">
    info
</span>
<div>
Your registration for membership is not complete.<strong><a href ="{% url 'management:complete_institutional_membership' id=membership.id%}">Click here to Complete your registration.</a>
 </storng>
</div>
</div>

management/templates/management/import_csv.html
{% extends "admin/base_site.html" %}
{% load static %}

{% block content %}
<h2>Import CSV</h2>
<form method="post" enctype="multipart/form-data">
    {% csrf_token %}
    {{ form.as_p }}
    <button type="submit" class="button">Upload</button>
</form>
{% endblock %}

management/templates/management/index.html
{% load static %}
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>NGS | Membership Portal</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/css/bootstrap.min.css" rel="stylesheet"
        integrity="sha384-T3c6CoIi6uLrA9TneNEoa7RxnatzjcDSCmG1MXxSR1GAsXEV/Dwwykc2MPK8M2HN" crossorigin="anonymous">
    <link rel="shortcut icon" href type="image/x-icon">
    <link rel="stylesheet" href="https://fonts.googleapis.com/icon?family=Material+Icons">
    <link rel="stylesheet"
        href="https://fonts.googleapis.com/css2?family=Material+Symbols+Outlined:opsz,wght,FILL,GRAD@24,400,0,0">
    <link rel="stylesheet"
        href="https://fonts.googleapis.com/css2?family=Material+Symbols+Rounded:opsz,wght,FILL,GRAD@20..48,100..700,0..1,-50..200">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.5.1/css/all.min.css" integrity="sha512-DTOQO9RWCH3ppGqcWaEA1BIZOC6xxalwEsw9c2QQeAIftl+Vegovlnee1c9QX4TctnWMn13TZye+giMm8e2LwA==" crossorigin="anonymous" referrerpolicy="no-referrer" />
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.5.1/css/all.min.css" integrity="sha512-DTOQO9RWCH3ppGqcWaEA1BIZOC6xxalwEsw9c2QQeAIftl+Vegovlnee1c9QX4TctnWMn13TZye+giMm8e2LwA==" crossorigin="anonymous" referrerpolicy="no-referrer" />
    <link rel="stylesheet" href="{% static 'css/style.css'%}">
</head>

<body>

    <nav class="navbar navbar-expand-lg sticky-top">
        <div class="container">
          <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarTogglerDemo03" aria-controls="navbarTogglerDemo03" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
          </button>
          <a class="navbar-brand" href="/">
            <img src="{% static 'images/fulllogo.jpg'%}" alt="">
          </a>
          <div class="collapse navbar-collapse" id="navbarTogglerDemo03">
            <ul class="navbar-nav me-auto mb-2 mb-lg-0">
              <li class="nav-item">
                <a class="nav-link active" aria-current="page" href="/">Home</a>
              </li>
              
              <li class="nav-item">
                <a class="nav-link" href="{% url 'management:membership_guidelines' %}">Membership</a>
              </li>
              <li class="nav-item">
                <a class="nav-link" href="{% url 'events:index_all_events'%}">Events</a>
              </li>
              <li class="nav-item">
                <a class="nav-link" href="https://ngeotechs.org/?page_id=1464" target="_blank">About NGS</a>
              </li>
            </ul>
            {% if user.is_authenticated %}
                <div class="user-img-nav">
                    <a href="{% url 'account:login_user' %}">
                        {% if request.user.role == 1 %}
                            <img src="https://ui-avatars.com/api/?name={{ request.user.full_name }}&rounded=true&background=FB802C&color=ffffff&size=28&bold=true">
                        {% else %}
                            {% if request.user.membership %}
                                <img src="{{ membership.pp_photo.url }}" alt="">
                            {% else %}
                                <img src="https://ui-avatars.com/api/?name={{ request.user.full_name }}&rounded=true&background=FB802C&color=ffffff&size=28&bold=true">
                            {% endif %}
                        {% endif %}
                    </a>
                </div>
            {% else %}
                <ul class="navbar-nav ms-auto">
                    <li class="nav-item">
                        <a class="nav-link auth-btn" href="{% url 'account:login_user' %}">Login</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link auth-btn" href="{% url 'account:signup' %}">Register</a>
                    </li>
                </ul>
            {% endif %}
          </div>
        </div>
    </nav>

    <div class="container">
        <div class="row my-5">
            <div class="col-md-12">
            <div id="carouselExampleCaptions" class="carousel slide" data-bs-ride="carousel">
                <div class="carousel-indicators">
                <button type="button" data-bs-target="#carouselExampleCaptions" data-bs-slide-to="0" class="active" aria-current="true" aria-label="Slide 1"></button>
                <button type="button" data-bs-target="#carouselExampleCaptions" data-bs-slide-to="1" aria-label="Slide 2"></button>
                <button type="button" data-bs-target="#carouselExampleCaptions" data-bs-slide-to="2" aria-label="Slide 3"></button>
                </div>
                <div class="carousel-inner">
                <div class="carousel-item active">
                  <img src="/static/images/membership_process.jpg" class="d-block w-100" alt="..." style="
                  object-fit: contain;">
                    <div class="story-overlay"></div>
                </div>
                {% comment %} <div class="carousel-item">
                    <img src="{% static 'images/banner2.jpg' %}" class="d-block w-100" alt="...">
                    <div class="story-overlay"></div>
                </div>
                <div class="carousel-item">
                    <img src="{% static 'images/banner3.jpg' %}" class="d-block w-100" alt="...">
                    <div class="story-overlay"></div>
                </div> {% endcomment %}
                </div>
                {% comment %} <button class="carousel-control-prev" type="button" data-bs-target="#carouselExampleCaptions" data-bs-slide="prev">
                <span class="carousel-control-prev-icon" aria-hidden="true"><i class="fa-solid fa-chevron-left"></i></span>
                <span class="visually-hidden">Previous</span>
                </button>
                <button class="carousel-control-next" type="button" data-bs-target="#carouselExampleCaptions" data-bs-slide="next">
                <span class="carousel-control-next-icon" aria-hidden="true"><i class="fa-solid fa-chevron-right"></i></span>
                <span class="visually-hidden">Next</span>
                </button> {% endcomment %}
            </div>
            </div>
        </div>
    </div>

    <div class="about-us-bg">
        <div class="container">
          <div class="row align-items-center">
            <div class="col-md-4">
              <div class="about-img">
                <img src="https://ngeotechs.org/wp-content/uploads/2019/05/image.jpg" alt="NGS">
              </div>
            </div>
            <div class="col-md-8 ps-5">
              <div class="about-us">
                <span>About us</span>
                <h3>Nepal Geotechnical Society</h3>
                <p>Nepal Geotechnical Society (NGS) was established in the pursuit of strengthening progressive national cooperation, enhancing exchange of information on research and developments in geotechnical engineering, geosciences, and other geo-related fields, and committing to the welfare of Nepal and the human society. It was formally registered with the Government of Nepal (then ‘Royal Nepalese Government’) in May 1994 (BS: Jestha 2051) by a group of dynamic and internationally motivated geotechnical engineers and academia of Nepal.</p>
                <div class="social-link-container">
                  <a href="https://www.facebook.com/ngeotechs"><i class="fa-brands fa-facebook-f"></i></a>
                  <a href="https://www.linkedin.com/company/90462440/admin/feed/posts/"><i class="fa-brands fa-linkedin-in"></i></a>
                  <a href="https://www.youtube.com/@nepalgeotechnicalsociety5216"><i class="fa-brands fa-youtube"></i></a>
                  <a href="https://twitter.com/ngeotechs"><i class="fa-brands fa-x-twitter"></i></a>
                </div>
              </div>
            </div>
          </div>
        </div>
    </div>

    <div class="container my-5">
      <div class="title-container">
        <h1 class="section-title">Events</h1>
        <a href="{% url 'events:index_all_events' %}"><i class="fa-solid fa-circle-arrow-right"></i></a>
      </div>
      <div class="row row-cols-1 row-cols-md-4 g-4 mt-3">
        {% for event in events %}
        <div class="col">
          <a href="{% url 'events:homepage_view_event' id=event.id %}">
            <div class="card h-100">
                <div class="card-body membership-card">
                    <span>{{ forloop.counter|stringformat:"02d" }}</span>
                    <h5 class="form-title">{{ event.name }}</h5>
                    <p class="card-text">{{ event.description|truncatewords:15 }}</p>
                </div>
            </div>
          </a>
        </div>
        {% endfor %}
    </div>
    </div>

    <div class="members-bg p-0">
      <div class="container">
        <div class="row">
          <div class="col-md-3 d-flex justify-content-end">
            <img src="{% static 'images/membership.png' %}" alt="">
          </div>
          <div class="col-md-9 py-5 ps-5">
            <div class="title-container">
              <h1 class="section-title" style="color: #ffffff;">Membership & Members</h1>
            </div>
            
            <div class="row row-cols-1 row-cols-md-4 g-4 mt-3">

              <div class="col">
                <a href="{% url 'management:honorary_members'%}">
                  <div class="card h-100">
                      <div class="card-body membership-card">
                          <span class="material-symbols-outlined"> person</span>
                          <h5 class="form-title">Honorary Members</h5>
                      </div>
                  </div>
                </a>
              </div>

              <div class="col">
                <a href="{% url 'management:general_members'%}">
                  <div class="card h-100">
                      <div class="card-body membership-card">
                          <span class="material-symbols-outlined"> person</span>
                          <h5 class="form-title">NGS <br>Members</h5>
                      </div>
                  </div>
                </a>
              </div>

              

              <div class="col">
                <a href="{% url 'management:institutional_members'%}">
                  <div class="card h-100">
                      <div class="card-body membership-card">
                          <span class="material-symbols-outlined"> maps_home_work</span>
                          <h5 class="form-title">Institutional Members</h5>
                      </div>
                  </div>
                </a>
              </div>

              <div class="col">
                <a href="{% url 'management:student_members'%}">
                  <div class="card h-100">
                      <div class="card-body membership-card">
                          <span class="material-symbols-outlined"> school</span>
                          <h5 class="form-title">Student <br>Members</h5>
                      </div>
                  </div>
                </a>
              </div>   
            </div>

            <!-- <div class="col">
              <a href="{% url 'management:lifetime_members'%}">
                <div class="card h-100">
                    <div class="card-body membership-card">
                        <span class="material-symbols-outlined"> person</span>
                        <h5 class="form-title">Lifetime Members</h5>
                    </div>
                </div>
              </a>
            </div> -->

          </div>
        </div>
      </div>
    </div>

    <div class="container my-5">
      <div class="title-container text-center">
        <h1 class="section-title text-center w-100">Frequently asked questions</h1>
      </div>
      <div class="faqs card mt-5">
        <div class="accordion accordion-flush education-details" id="education">
          {% for faq in faqs %}
          <div class="accordion-item">
              <h2 class="accordion-header">
                  <button class="accordion-button" type="button" data-bs-toggle="collapse" data-bs-target="#faq-{{ faq.id }}" aria-expanded="false" aria-controls="faq-{{ faq.id }}">
                     {{ faq.question }}
                  </button>
              </h2>
              <div id="faq-{{ faq.id }}" class="accordion-collapse collapse {% if forloop.counter == 1 %} show {% endif %}" data-bs-parent="#education">
                <p>{{ faq.answer }}</p>
              </div>
          </div>
         {% endfor %}
      </div>
      </div>
    </div>

    <div class="footer">
      <div class="container footer-content">
        <div class="copyright">
          <p>© 2023 Nepal Geotechnical Society</p>
        </div>
        <div class="developed-by">
          <p class="me-3">Developed by</p>
          <a href="https://kantipurinfotech.com/">
            <img src="{% static 'images/kantipur.svg' %}" alt="">
          </a>
        </div>
      </div>
    </div>
    
</body>

<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/js/bootstrap.bundle.min.js"
    integrity="sha384-C6RzsynM9kWDrMNeT87bh95OGNyZPhcTNXj1NW7RuBCsyN/o0jlpcV8Qyq46cDfL"
    crossorigin="anonymous"></script>





</html>