events/urls.py
from django.contrib import admin
from django.urls import path

from . import views

app_name='events'
urlpatterns = [
    path('event-list',views.all_events,name="all_events"),
    path('event-add<int:id>',views.events_add,name="edit_event"),
    path('<int:id>/delete/', views.delete_event, name='delete_event'),

    path('event-add',views.events_add,name="eventadd"),
    path('view-event/<int:id>',views.view_event,name='view_event'),

    #homepage view of event
    path('all-events-index',views.index_all_events,name='index_all_events'),
    path('homepage-view-event/<int:id>',views.homepage_view_event,name='homepage_view_event'),
    #for participation
    path('participate/<int:event_id>/', views.participate, name='participate'),
    # path('participation/', views.regunauth, name="participation"),
    #payment for events
    path('event/payment/process/<int:event_id>/', views.auth_payment_process, name='auth_payment_process'),
    path('event/payment/process/<int:event_id>/<str:name>/<str:email>/<int:phone>', views.unauth_payment_process, name='unauth_payment_process'),
    # path('event/payment/done/', views.payment_done, name='payment_done'),

    # path('participation-list/', views.participatorlist, name='participation_list'),

    path('participation_list/', views.participatorlist, name='participation_list'),
    # URL pattern for showing participation list for a specific event
    path('participation_list/<int:event_id>/', views.participatorlist, name='event_participation_list'),
    path('not_going_participants/<int:event_id>/', views.not_going_participants, name='not_going_participants'),
]

membership/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf import settings
from django.contrib.auth import views as auth_views
from account.views import CustomPasswordResetView
from django.conf.urls.static import static

urlpatterns = [
    path("admin/", admin.site.urls),
    path('',include('management.urls')),
    path('account/',include('account.urls')),
    path('notifications/',include('notification.urls')),
    path('events',include('events.urls')),
     path(
        "reset-password/",
        CustomPasswordResetView.as_view(
            template_name="account/forget_password.html"
        ),
        name="reset_password",
    ),
    path(
        "password_reset/done/",
        auth_views.PasswordResetDoneView.as_view(
            template_name='account/password_reset_done.html'
        ),
        name="password_reset_done",
    ),
    path(
        "reset/<uidb64>/<token>/",
        auth_views.PasswordResetConfirmView.as_view(
            template_name="account/reset_password.html"
        ),
        name='password_reset_confirm',
    ),
    path(
        "reset/done/",
        auth_views.PasswordResetCompleteView.as_view(
            template_name='account/password_reset_complete.html'
        ),
        name="password_reset_complete",
    ),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

notification/urls.py
from django.contrib import admin
from django.urls import path

from . import views


app_name='notification'
urlpatterns = [
    path('create-group',views.create_group,name='create_group'),
    path('edit-group/<int:id>',views.create_group,name='edit_group'),
    path('all-groups',views.all_groups,name='all_groups'),
    path('delete_group/<int:id>/', views.delete_group, name='delete_group'),
    path('view-group/<int:id>',views.view_group,name='view_group'),
    path('create-notification',views.create_notification,name='create_notification'),
    path('edit-notification/<int:id>',views.create_notification,name="edit_notification"),
    path('view-notification/<int:id>',views.view_notification,name="view_notification"),
    path('all-notifications',views.all_notifications,name='all_notifications'),
    path('create-update-groups/',views.create_or_update_groups_and_missing_members, name='create_or_update_groups_and_missing_members'),

]

notification/models.py
from collections.abc import Iterable
from django.db import models
from account.models import CustomUser
from django.utils import timezone
# Create your models here.
class Groups(models.Model):
    name = models.CharField(max_length = 100)
    description = models.CharField(max_length = 2000)
    users = models.ManyToManyField(CustomUser,related_name='notification_groups')
    created_at= models.DateTimeField(auto_now_add=True,null=True)

class Notifications(models.Model):
    created_at=models.DateTimeField(auto_now_add=True,null=True)
    subject = models.CharField(max_length = 100)
    description = models.CharField(max_length = 2000)
    groups = models.ManyToManyField(Groups,related_name='groups')
    status = models.BooleanField()

    def __str__(self) -> str:
        return self.subject

notification/forms.py
from django import forms
from .models import Groups,Notifications

class CreateGroupForm(forms.ModelForm):

    class Meta:
        model = Groups
        fields = ['name','description','users']
    

class NotificationForm(forms.ModelForm):

    class Meta:
        model = Notifications
        fields =['subject','description','groups','status']

notification/views.py
from django.shortcuts import render,redirect, HttpResponse, get_object_or_404
from account.models import CustomUser
from .models import (Notifications,Groups)
from .forms import CreateGroupForm,NotificationForm
from management.models import Membership, GeneralMembership,InstitutionalMembership
from django.contrib import messages

# Create your views here.

from django.http import HttpResponse
from django.core.exceptions import ObjectDoesNotExist
from .models import Groups

def create_or_update_groups(request):
    group_names = [
        ('All Members', "This group contains all registered members."),
        ('General Members', "This group contains all the members with general membership."),
        ('Lifetime Members', "This group contains all the members with lifetime membership."),
        ('Student Members', "This group contains all the members with student membership."),
        ('Institutional Members', "This group contains all the members with institutional membership."),
    ]

    groups = {}
    for name, description in group_names:
        group, created = Groups.objects.get_or_create(name=name, defaults={'description': description})
        groups[name] = group

    verified_users = Membership.objects.select_subclasses().filter(verification=True)
    gm_users = verified_users.filter(membership_type=1)
    life_users = verified_users.filter(membership_type=3)
    st_users = verified_users.filter(membership_type=4)
    ins_users = Membership.objects.filter(verification=True, membership_type=2)

    groups['All Members'].users.set(verified_users.values_list('associated_user', flat=True))
    groups['General Members'].users.set(gm_users.values_list('associated_user', flat=True))
    groups['Lifetime Members'].users.set(life_users.values_list('associated_user', flat=True))
    groups['Student Members'].users.set(st_users.values_list('associated_user', flat=True))
    groups['Institutional Members'].users.set(ins_users.values_list('associated_user', flat=True))

    return HttpResponse("Groups Created or Updated")

def update_missing_members():
    verified_users = Membership.objects.select_subclasses().filter(verification=True)
    
    for user in verified_users:
        group_name = 'All Members'
        if user.membership_type == 1:
            group_name = 'General Members'
        elif user.membership_type == 2:
            group_name = 'Institutional Members'
        elif user.membership_type == 3:
            group_name = 'Lifetime Members'
        elif user.membership_type == 4:
            group_name = 'Student Members'

        group = Groups.objects.get(name=group_name)
        if not group.users.filter(id=user.associated_user.id).exists():
            group.users.add(user.associated_user.id)

    return HttpResponse("Missing Members Updated")

def create_or_update_groups_and_missing_members(request):
    create_or_update_groups(request)
    update_missing_members()
    return HttpResponse("Groups Created/Updated and Missing Members Updated")


# def create_initial_group(request):
#     """ Only to create group here. First"""
#     verified_users = Membership.objects.select_subclasses().filter(verification=True)
#     gm_users = Membership.objects.select_subclasses().filter(verification=True,membership_type =1)
#     life_users = Membership.objects.select_subclasses().filter(verification=True,membership_type =3)
#     st_users = Membership.objects.select_subclasses().filter(verification=True,membership_type =4)
#     ins_users = Membership.objects.filter(verification=True,membership_type =2)
#     a=Groups.objects.create(name='All Members',description="This group contains all registered members.")
#     b=Groups.objects.create(name='General Members',description="This group contains all the members with general membership.")
#     c=Groups.objects.create(name='Lifetime Members',description="This group contains all the members with lifetime membership.")
#     d=Groups.objects.create(name='Student Members',description="This group contains all the members with student membership.")
#     e=Groups.objects.create(name='Institutional Members',description="This group contains all the members with institutional membership.")
#     a.users.set(verified_users.values_list('associated_user', flat=True))
#     b.users.set(gm_users.values_list('associated_user', flat=True))
#     c.users.set(life_users.values_list('associated_user', flat=True))
#     d.users.set(st_users.values_list('associated_user', flat=True))
#     e.users.set(ins_users.values_list('associated_user', flat=True))
#     return HttpResponse("Seed Groups Created")

def create_group(request,id=None):
    all_users = CustomUser.objects.all()
    if id:
        group = get_object_or_404(Groups, id=id)
        form = CreateGroupForm(request.POST or None, instance=group)
    else:
        group=None
        form = CreateGroupForm(request.POST or None)
    if request.method == 'POST':
        if form.is_valid():
            group= form.save()
            if id:
                messages.success(request, 'Notification mailing group updated successfully.')
            else:
                messages.success(request, 'Notification mailing group created successfully.')
            return redirect('notification:all_groups')
        else:
            print(form.errors)
    else:
        pass
    context={
        'all_users':all_users,
        'form':form,
        'group':group
    }
    return render(request,'notification/create_group.html',context)

def all_groups(request):
    groups= Groups.objects.all()
    context={
        'groups':groups,
    }
    return render(request,'notification/all_groups.html',context)

def view_group(request,id):
    group=get_object_or_404(Groups,id=id)
    context={
        'group': group,
    }
    return render(request,'notification/view_group.html',context)

def delete_group(request, id):
    group = get_object_or_404(Groups, id=id)
    if request.method == "POST":
        group.delete()
        messages.success(request, "Notification mailing group deleted successfully.")
    return redirect('notification:all_groups')

# def create_notification(request,id=None):
#     groups = Groups.objects.all()
    
#     # If id is provided, retrieve the notification instance
#     notification_instance = None
#     if id:
#         notification_instance = get_object_or_404(Notifications, id=id)
#     form = NotificationForm(request.POST or None,request.FILES or None,instance=notification_instance)
#     if request.method == 'POST':
#         print(request.POST)
#         if form.is_valid():
#             form.save()
#             return redirect('notification:all_notifications')
#         else:
#             print(form.errors)
#     context={
#         'groups':groups,
#         'form':form
#     }
#     return render(request,'notification/create_notification.html',context)

def create_notification(request, id=None):
    groups = Groups.objects.all()

    # If id is provided, retrieve the notification instance
    notification_instance = None
    if id:
        notification_instance = get_object_or_404(Notifications, id=id)
    form = NotificationForm(request.POST or None, request.FILES or None, instance=notification_instance)
    if request.method == 'POST':
        print(request.POST)
        if form.is_valid():
            notification = form.save(commit=False)
            notification.status = request.POST.get('status') == '1'
            notification.save()
            form.save_m2m()
            return redirect('notification:all_notifications')
        else:
            print(form.errors)
    context = {
        'groups': groups,
        'form': form
    }
    return render(request, 'notification/create_notification.html', context)


def all_notifications(request):
    notifications= Notifications.objects.all()
    context={
        'notifications':notifications,
    }
    return render(request,'notification/all_notifications.html',context)


def view_notification(request,id):
    notification_instance = get_object_or_404(Notifications, id=id)
    context={
        'notification':notification_instance
    }
    return render(request,'notification/view_notification.html',context)

notification/templates/notification/all_groups.html
{% extends 'login_layout/layout.html' %}
{% load static %}
{% block content %}

            <div class="col-md-9 my-profile-w-80 g-0">
                {% include 'management/topbar.html' %}

                <div class="main-section-container">
                    <div class="row back-link">
                        <a href="#" onclick="history.back()">
                            <div class="icon-box"><span class="material-symbols-outlined">
                                    arrow_back_ios
                                </span>
                            </div>Notification groups
                        </a>
                    </div>
                    {% if messages %}
                    {% for message in messages %}
                    {% if message.tags == 'success' %}
                    <div class="alert alert-primary d-flex align-items-center alert-dismissible fade show mt-4"
                        role="alert">
                        <span class="material-symbols-outlined me-2">
                            info
                        </span>
                        <div>
                            {{ message|escape }}
                        </div>
                        <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
                    </div>
                    {% elif message.tags == 'error' %}
                    <div class="alert alert-danger d-flex align-items-center alert-dismissible fade show mt-4"
                        role="alert">
                        <span class="material-symbols-outlined me-2">
                            info
                        </span>
                        <div>
                            {{ message|escape }} Notification mailing group deleted successfully.
                        </div>
                        <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
                    </div>
                    {% elif message.tags == 'info' %}
                    <div class="alert alert-warning d-flex align-items-center alert-dismissible fade show mt-4"
                        role="alert">
                        <span class="material-symbols-outlined me-2">
                            info
                        </span>
                        <div>
                            {{ message|escape }} Notification mailing group updated successfully.
                        </div>
                        <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
                    </div>
                    {% endif %}
                    {% endfor %}
                    {% endif %} 

                    <div class="row row-cols-1 row-cols-md-4 g-4 mt-4">
                        {% for group in groups %}
                        <div class="col">
                            <div class="card h-100">
                                <div class="card-body membership-card">
                                    <span>{{ forloop.counter|stringformat:"02d" }}</span>
                                    <h5 class="form-title">{{ group.name }}</h5>
                                    <p class="card-text">{{ group.description }}</p>
                                </div>
                                <div class="card-footer d-flex">
                                    <a href="{% url 'notification:view_group' id=group.id %}" class="btn btn-apply">View Details</a>
                                    <div class="d-flex kit-action-com">
                                        <div class="action-btn-pen">
                                            <a href="{% url 'notification:edit_group' id=group.id %}"><span class="material-symbols-outlined">
                                                    edit
                                                </span>
                                            </a>
                                        </div>
                                        <div class="action-btn-dtl">
                                            <button type="button" class="btn btn-danger" data-bs-toggle="modal" data-bs-target="#deleteModal" data-id="{{ group.id }}">
                                                <span class="material-symbols-outlined">close</span>
                                            </button>
                                        </div>
                                    </div>
                                </div>
                            </div>
                        </div>
                        {% endfor %}

                    </div>

                </div>
            </div>


<!-- Delete Confirmation Modal -->
<div class="modal fade" id="deleteModal" tabindex="-1" aria-labelledby="deleteModalLabel" aria-hidden="true">
    <div class="modal-dialog">
        <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title" id="deleteModalLabel">Delete Group</h5>
                <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
            </div>
            <div class="modal-body">
                Are you sure you want to delete this group?
            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Cancel</button>
                <form method="post" action="{% url 'notification:delete_group' id=0 %}" id="deleteForm">
                    {% csrf_token %}
                    <button type="submit" class="btn btn-danger">Delete</button>
                </form>
            </div>
        </div>
    </div>
</div>

<script>
document.addEventListener('DOMContentLoaded', function() {
    var deleteModal = document.getElementById('deleteModal');
    deleteModal.addEventListener('show.bs.modal', function (event) {
        var button = event.relatedTarget; // Button that triggered the modal
        var groupId = button.getAttribute('data-id'); // Extract info from data-* attributes
        var deleteForm = document.getElementById('deleteForm');
        var action = deleteForm.getAttribute('action');
        deleteForm.setAttribute('action', action.replace('0', groupId));
    });
});
</script>
{% endblock %}

notification/templates/notification/create_group.html
{% extends 'login_layout/layout.html' %}
{% load static %}
{% block content %}
            <div class="col-md-9 my-profile-w-80 g-0">
                {% include 'management/topbar.html' %}
               {% block form %}
                <div class="main-section-container">
                    <div class="row back-link">
                        <a href="#" onclick="history.back()">
                            <div class="icon-box"><span class="material-symbols-outlined">
                                arrow_back_ios
                                </span></div>Notification <span style="color: #808080; margin-left: 5px;"> > Create group</span></a>
                    </div>
                    <div class="multilevel-form">
                        {% if group %}
                        <form action ="{% url 'notification:edit_group' id=form.instance.id  %}" method='post'>
                        {% else %}
                        <form action ="{% url 'notification:create_group'%}" method='post'>
                        {% endif %}
                            {% csrf_token %}
                            <div class="step" id="step1">
                                <h3 class="form-title">Create notification group</h3>
                                <hr>
            
                                <div class="row mb-3">
                                    <div class="col-md-12">
                                        <label class="form-label cm">Group name <span class="required-text">*</span></label>
                                        <input type="text" class="form-control cm" placeholder="Enter group name" name='name' {% if form.name.value %} value={{ form.name.value }}{% endif %} {% if group %}%value={{ group.name }}{% endif %}required>
                                    </div>
                                </div>

                                <div class="row mb-3">
                                    <div class="col-md-12">
                                        <label class="form-label cm">Group description</label>
                                        <textarea class="form-control cm" placeholder="Enter group description" rows="5" name='description'>{% if form.name.value %}{{ form.description.value }}{% endif %}{% if group %}{{ group.description }} {% endif %} </textarea>
                                    </div>
                                </div>

                                <div class="row mb-3">
                                    <div class="col-md-12">
                                        <label class="form-label cm">Select contacts <span class="required-text">*</span></label>
                                        <!-- Add Select All checkbox -->
                                        <div>
                                            <input type="checkbox" id="select-all-checkbox"> Select All
                                        </div>
                                        <select id="contact-list" class="contact-list js-states form-control cm" name="users" multiple="multiple">
                                            {% for user in all_users %}
                                            <option value="{{ user.id }}" {% if form.instance and user in form.instance.users.all %}selected{% endif %}>{{ user.email }}</option>
                                            {% endfor %}
                                        </select>
                                    </div>
                                </div>
                                
                                <script>
                                    document.getElementById('select-all-checkbox').addEventListener('change', function() {
                                        var selectAllChecked = this.checked;
                                        var select = document.getElementById('contact-list');
                                        for (var i = 0; i < select.options.length; i++) {
                                            select.options[i].selected = selectAllChecked;
                                        }
                                        // Trigger an input event on the select element to update the UI
                                        var event = new Event('input', { bubbles: true });
                                        select.dispatchEvent(event);
                                    });
                                </script>
                                
                                
                                <div class="button-container mt-2 d-flex justify-content-end">
                                    <button type="submit" class="submit-btn btn" onclick="nextStep(this)">
                                        {% if form.group %}Update{% else %}Create Group{% endif %}</button>
                                </div>
                            </div>
                        </form>
                    </div>

                </div>
                {% endblock %}
                
            </div>
{% endblock %}

{% block scripts %}
<script src="https://cdn.jsdelivr.net/npm/select2@4.1.0-rc.0/dist/js/select2.min.js"></script>
<script>
    $(document).ready(function() {
        $(".contact-list").select2({
            placeholder: "Select contacts"
        });
    }); 
</script>
{% endblock %}

notification/templates/notification/create_notification.html
{% extends 'notification/create_group.html' %}
{% load static %}
         {% block form %}
                <div class="main-section-container">
                    <div class="row back-link">
                        <a href="#" onclick="history.back()">
                            <div class="icon-box"><span class="material-symbols-outlined">
                                arrow_back_ios
                                </span></div>Notification <span style="color: #808080; margin-left: 5px;"> > Create mail</span></a>
                    </div>

                    <div class="multilevel-form">
                        {% if notification %}
                        <form method ='post',action='{% url 'notification:edit_notification' id=form.instance.id %}'>
                            {% else %}
                        <form method ='post', action={% url 'notification:create_notification' %}>
                            {% endif %}
                            {% csrf_token %}
                            <div class="step" id="step1">
                                <h3 class="form-title">Create notification mail</h3>
                                <hr>
            
                                <div class="row mb-3">
                                    <div class="col-md-12">
                                        <label class="form-label cm">Mail subject <span class="required-text">*</span></label>
                                        <input type="text" class="form-control cm" placeholder="Enter mail subject" name='subject'{% if form.instance %}value='{{ form.instance.subject }}'{% endif %} required>
                                    </div>
                                </div>

                                <div class="row mb-3">
                                    <div class="col-md-12">
                                        <label class="form-label cm">Mail description</label>
                                        <textarea class="form-control cm" placeholder="Enter mail description" rows="5" name='description'>{% if form.instance %}{{ form.instance.description }}{% endif %}</textarea>
                                    </div>
                                </div>

                                <div class="row mb-3">
                                    <div class="col-md-12">
                                        <label class="form-label cm">Select groups <span class="required-text">*</span></label>
                                        <select class="contact-list js-states form-control cm" name="groups" multiple="multiple">
                                            {% for group in groups %}
                                            <option value="{{ group.id }}" {% if form.instance and group in form.instance.groups.all %}selected{% endif %}>{{ group.name }}</option>
                                            {% endfor %}
                                        </select>
                                    </div>
                                </div>

                                <div class="button-container mt-2 d-flex justify-content-end">
                                    <button type="submit" class="btn btn-secondary prev-btn me-2"  name='status' value='0'>Save as draft</button>
                                    <button type="submit" class="btn submit-btn" name='status' value='1'>Send mail</button>
                                </div>
                            </div>
                        </form>
                    </div>

                </div>
        {% endblock %}
                
          